waystones:
  - name: lodestone
    blocks:
      - { name: smooth_stone_slab, x: 0, y: 1, z: 0 }
      - { name: lodestone, x: 0, y: 2, z: 0 }
      - { name: light, x: 0, y: 3, z: 0 }
    blockDisplays:
      - { name: smooth_stone, offset: { x: 0.075, y: -1.2, z: 0.075 }, scale: { x: 0.85, y: 0.85, z: 0.85 } }
      - { name: smooth_stone, offset: { x: 0.2, y: -1.6, z: 0.2 }, scale: { x: 0.6, y: 0.6, z: 0.6 } }
      - { name: smooth_stone, offset: { x: 0.075, y: -0.65, z: 0.075 }, scale: { x: 0.85, y: 0.85, z: 0.85 } }
    crafting:
      - air
      - ender_eye
      - air
      - enchanted_book
      - lodestone
      - enchanted_book
      - smooth_stone
      - smooth_stone
      - smooth_stone
