name: WaystonesPlus
version: "1.2.3"
main: org.sweetrazory.waystonesplus.Main
api-version: "1.19"
commands:
  waystones:
    description: "Main command"
    aliases:
      - waystone
      - waystonesplus
      - waystoneplus
      - wsp